# Generated by Codex on 2026-02-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_soc_admin_role"),
        ("accounts", "0002_alter_user_options"),
    ]

    operations = []
