# Generated by Django 5.0.9 on 2026-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_add_soc_admin_role_0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganization',
            name='role',
            field=models.CharField(choices=[('security_lead', 'Security Lead'), ('developer', 'Developer'), ('executive', 'Executive'), ('soc_admin', 'SOC Admin')], default='security_lead', max_length=50),
        ),
    ]
