# Generated by Django 5.0.9 on 2026-02-16 00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_userorganization_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationScanPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("ssrf_high_risk_enabled", models.BooleanField(default=False)),
                ("ssrf_allow_metadata", models.BooleanField(default=False)),
                ("ssrf_allowlist", models.JSONField(blank=True, default=dict, help_text='Expected shape: {"domains": [], "cidrs": [], "urls": []}.')),
                (
                    "organization",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="scan_policy", to="accounts.organization"),
                ),
            ],
        ),
    ]

