# Generated by Django 5.0.9 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="high_risk_ssrf_authorized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="asset",
            name="high_risk_ssrf_authorization_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="asset",
            name="high_risk_ssrf_authorization_notes",
            field=models.TextField(blank=True),
        ),
    ]

