# Generated by Django 5.0.9 on 2026-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='scope',
            field=models.CharField(choices=[('web', 'Web'), ('code', 'Code'), ('network', 'Network'), ('cloud', 'Cloud'), ('combined', 'Combined')], default='combined', max_length=20),
        ),
    ]
