# Generated by Django 5.0.9 on 2026-02-06 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userorganization_role'),
        ('assets', '0001_initial'),
        ('code_security', '0001_initial'),
        ('scans', '0002_scanjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='scan_type',
            field=models.CharField(choices=[('code', 'Code'), ('network', 'Network'), ('web', 'Web'), ('api', 'API'), ('infrastructure', 'Infrastructure')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scan_type', models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('code', 'Code'), ('network', 'Network'), ('infrastructure', 'Infrastructure')], max_length=30)),
                ('target', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('client_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_requests', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_requests', to='accounts.organization')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_requests', to='code_security.coderepository')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scanjob',
            name='scan_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='scans.scanrequest'),
        ),
    ]
