# Generated by Django 5.0.9 on 2026-02-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0001_initial"),
        ("scans", "0003_alter_scanjob_scan_type_scanrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="service_request",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scan_jobs", to="service_requests.servicerequest"),
        ),
    ]
