# Generated by Django 5.0.9 on 2026-02-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_security', '__first__'),
        ('scans', '0008_scanjob_initiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='cloud_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='cloud_security.cloudaccount'),
        ),
        migrations.AddField(
            model_name='scanschedule',
            name='cloud_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_schedules', to='cloud_security.cloudaccount'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('code', 'Code'), ('network', 'Network'), ('infrastructure', 'Infrastructure'), ('cloud', 'Cloud')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='scan_type',
            field=models.CharField(choices=[('code', 'Code'), ('network', 'Network'), ('web', 'Web'), ('api', 'API'), ('infrastructure', 'Infrastructure'), ('cloud', 'Cloud')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='scan_type',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('code', 'Code'), ('network', 'Network'), ('infrastructure', 'Infrastructure'), ('cloud', 'Cloud')], max_length=30),
        ),
    ]
