# Generated by Django 5.0.9 on 2026-02-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_security', '0002_add_scan_job_service_request'),
        ('network_security', '0002_networkfinding_status_fields'),
    ]

    operations = [
    ]
