# Generated by Django 5.0.9 on 2026-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_security', '0005_networkfinding_confidence_rationale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkfinding',
            name='finding_type',
            field=models.CharField(choices=[('exposed_service', 'Exposed Service'), ('segmentation_risk', 'Segmentation Risk'), ('misconfiguration', 'Misconfiguration'), ('active_validation', 'Active Security Validation')], max_length=50),
        ),
    ]
