# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_security", "0006_alter_networkfinding_finding_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkfinding",
            name="cvss_vector",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]

