# Generated by Django 5.0.9 on 2026-02-07

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("assets", "0001_initial"),
        ("scans", "0003_alter_scanjob_scan_type_scanrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("requested_role", models.CharField(choices=[("executive", "Executive"), ("developer", "Developer"), ("security_lead", "Security Lead")], max_length=40)),
                ("service_type", models.CharField(choices=[("CODE_SECRETS_SCAN", "Code Secrets Scan"), ("DEPENDENCY_VULN_SCAN", "Dependency Vulnerability Scan"), ("NETWORK_CONFIGURATION_SCAN", "Network Configuration Scan")], max_length=60)),
                ("scope", models.CharField(blank=True, choices=[("repository", "Repository"), ("asset", "Asset"), ("ip_cidr", "IP / CIDR"), ("domain", "Domain / URL")], max_length=40)),
                ("repository_url", models.URLField(blank=True)),
                ("ip_cidr", models.CharField(blank=True, max_length=64)),
                ("domain_url", models.CharField(blank=True, max_length=255)),
                ("justification", models.TextField()),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("RUNNING", "Running"), ("COMPLETED", "Completed")], default="PENDING", max_length=20)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_service_requests", to=settings.AUTH_USER_MODEL)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_requests", to="assets.asset")),
                ("linked_scan_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_requests", to="scans.scanjob")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_requests", to="accounts.organization")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_requests", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
