# Generated by Django 5.0.9 on 2026-02-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('CODE_SECRETS_SCAN', 'Code Secrets Scan'), ('DEPENDENCY_VULN_SCAN', 'Dependency Vulnerability Scan'), ('NETWORK_CONFIGURATION_SCAN', 'Network Configuration Scan'), ('WEB_EXPOSURE_SCAN', 'Web Exposure Scan'), ('API_SECURITY_SCAN', 'API Security Scan'), ('INFRASTRUCTURE_HARDENING_SCAN', 'Infrastructure Hardening Scan')], max_length=60),
        ),
    ]
