# Generated by Django 5.0.9 on 2026-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_alter_servicerequest_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('CODE_SECRETS_SCAN', 'Code Secrets Scan'), ('DEPENDENCY_VULN_SCAN', 'Dependency Vulnerability Scan'), ('CODE_COMPLIANCE_SCAN', 'Code Standards Compliance (Full)'), ('CODE_COMPLIANCE_PYTHON', 'Python PEP8 Compliance'), ('CODE_COMPLIANCE_HTML', 'HTML Standards Compliance'), ('CODE_COMPLIANCE_CSS', 'CSS Standards Compliance'), ('CODE_COMPLIANCE_JAVASCRIPT', 'JavaScript Standards Compliance'), ('CODE_COMPLIANCE_REACT', 'React Standards Compliance'), ('NETWORK_CONFIGURATION_SCAN', 'Network Configuration Scan'), ('WEB_EXPOSURE_SCAN', 'Web Exposure Scan'), ('API_SECURITY_SCAN', 'API Security Scan'), ('INFRASTRUCTURE_HARDENING_SCAN', 'Infrastructure Hardening Scan')], max_length=60),
        ),
    ]
