# Generated by Django 5.0.9 on 2026-02-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_security', '__first__'),
        ('service_requests', '0004_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cloud_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='cloud_security.cloudaccount'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='scope',
            field=models.CharField(blank=True, choices=[('repository', 'Repository'), ('asset', 'Asset'), ('ip_cidr', 'IP / CIDR'), ('domain', 'Domain / URL'), ('cloud', 'Cloud Account')], max_length=40),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('CODE_SECRETS_SCAN', 'Code Secrets Scan'), ('DEPENDENCY_VULN_SCAN', 'Dependency Vulnerability Scan'), ('CODE_COMPLIANCE_SCAN', 'Code Standards Compliance (Full)'), ('CODE_COMPLIANCE_PYTHON', 'Python PEP8 Compliance'), ('CODE_COMPLIANCE_HTML', 'HTML Standards Compliance'), ('CODE_COMPLIANCE_CSS', 'CSS Standards Compliance'), ('CODE_COMPLIANCE_JAVASCRIPT', 'JavaScript Standards Compliance'), ('CODE_COMPLIANCE_REACT', 'React Standards Compliance'), ('NETWORK_CONFIGURATION_SCAN', 'Network Configuration Scan'), ('WEB_EXPOSURE_SCAN', 'Web Exposure Scan'), ('API_SECURITY_SCAN', 'API Security Scan'), ('INFRASTRUCTURE_HARDENING_SCAN', 'Infrastructure Hardening Scan'), ('CLOUD_POSTURE_SCAN', 'Cloud Posture Scan')], max_length=60),
        ),
    ]
