# Generated by Django 5.0.9 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_requests", "0005_servicerequest_cloud_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="ownership_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="high_risk_ssrf",
            field=models.BooleanField(default=False),
        ),
    ]

