# Generated by Django 5.0.9 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_requests", "0006_servicerequest_high_risk_ssrf_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="authorization_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="authorization_notes",
            field=models.TextField(blank=True),
        ),
    ]

