# Generated by Django 5.0.9 on 2026-02-08 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_userorganization_role'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('aws_account_id', models.CharField(blank=True, max_length=32)),
                ('aws_role_arn', models.CharField(blank=True, max_length=512)),
                ('aws_external_id', models.CharField(blank=True, max_length=128)),
                ('azure_tenant_id', models.CharField(blank=True, max_length=128)),
                ('azure_client_id', models.CharField(blank=True, max_length=128)),
                ('azure_subscription_id', models.CharField(blank=True, max_length=128)),
                ('_azure_client_secret', models.TextField(blank=True, db_column='azure_client_secret')),
                ('gcp_project_id', models.CharField(blank=True, max_length=128)),
                ('_gcp_service_account', models.TextField(blank=True, db_column='gcp_service_account')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_accounts', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='moderate', max_length=16)),
                ('description', models.TextField()),
                ('remediation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('compliance', models.JSONField(blank=True, default=list)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_findings', to='assets.asset')),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='cloud_security.cloudaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_findings', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
