# Generated by Django 5.0.9 on 2026-02-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_security", "0001_initial"),
        ("scans", "0009_scanjob_cloud_account_scanschedule_cloud_account_and_more"),
        ("service_requests", "0005_servicerequest_cloud_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudfinding",
            name="scan_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cloud_findings",
                to="scans.scanjob",
            ),
        ),
        migrations.AddField(
            model_name="cloudfinding",
            name="service_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cloud_findings",
                to="service_requests.servicerequest",
            ),
        ),
    ]
