# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_security", "0002_cloudfinding_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudfinding",
            name="cvss_vector",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]

