# Generated by Django 5.0.9 on 2026-02-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_security", "0001_initial"),
        ("scans", "0004_add_scanjob_service_request"),
        ("service_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codefinding",
            name="scan_job",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="code_findings", to="scans.scanjob"),
        ),
        migrations.AddField(
            model_name="codefinding",
            name="service_request",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="code_findings", to="service_requests.servicerequest"),
        ),
    ]
