# Generated by Django 5.0.9 on 2026-02-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_security', '0002_add_scan_job_service_request'),
        ('code_security', '0002_codefinding_secret_fields'),
    ]

    operations = [
    ]
