# Generated by Django 5.0.9 on 2026-02-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_security', '0003_codefinding_nullable_secret_fields'),
        ('code_security', '0003_merge_20260207_0908'),
    ]

    operations = [
    ]
