# Generated by Django 5.0.9 on 2026-02-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_security', '0004_codefinding_status_fields'),
        ('code_security', '0004_merge_20260207_0937'),
    ]

    operations = [
    ]
