# Generated by Django 5.0.9 on 2026-02-07 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_security', '0005_merge_20260207_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepositorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_type', models.CharField(max_length=64)),
                ('file_hashes', models.JSONField(blank=True, default=dict)),
                ('files_scanned', models.PositiveIntegerField(default=0)),
                ('files_changed', models.PositiveIntegerField(default=0)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='code_security.coderepository')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
