# Generated by Django 5.0.9 on 2026-02-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='findingdisposition',
            new_name='triage_find_organiz_3d22d7_idx',
            old_name='triage_find_organiza_5b6a06_idx',
        ),
        migrations.RenameIndex(
            model_name='findingdisposition',
            new_name='triage_find_content_c96c8f_idx',
            old_name='triage_find_content__f8f76a_idx',
        ),
        migrations.RenameIndex(
            model_name='findingdisposition',
            new_name='triage_find_expires_e3b085_idx',
            old_name='triage_find_expires__a2fe01_idx',
        ),
    ]
